# Generated by Django 4.2.4 on 2023-08-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LittleLemonAPI", "0003_alter_cart_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="items",
        ),
        migrations.AddField(
            model_name="cart",
            name="menu_items",
            field=models.ManyToManyField(to="LittleLemonAPI.menuitem"),
        ),
    ]
