# Generated by Django 4.2.4 on 2023-08-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LittleLemonAPI", "0007_order_delivery_crew"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
    ]
